
import { initializeApp } from "firebase/app";


const firebaseConfig = {
  apiKey: "AIzaSyCpBdKYWZKa7zLFdr1CNizllaXQaGQZtKo",
  authDomain: "login-practice-108c6.firebaseapp.com",
  projectId: "login-practice-108c6",
  storageBucket: "login-practice-108c6.firebasestorage.app",
  messagingSenderId: "666682673874",
  appId: "1:666682673874:web:a4c29308499a4f7c483b0b"
};


const app = initializeApp(firebaseConfig);

export default app